favicon: https://cdn.wuyuan.dev/sitelogo.png #è¿™é‡Œæ›¿æ¢æˆç½‘ç«™logoåœ°å€

# _config.yun.yml
medium_zoom: true

scrollreveal:
  enable: true
  targets:
    - .post-card
    - .markdown-body img

cursor:
  enable: true
  default: https://cdn.yunyoujun.cn/css/md-cursors/pointer.cur
  pointer: https://cdn.yunyoujun.cn/css/md-cursors/link.cur
  text: https://cdn.yunyoujun.cn/css/md-cursors/text.cur

fireworks:
  enable: true
  colors:
    - "102, 167, 221"
    - "62, 131, 225"
    - "33, 78, 194"

social:
  - name: RSS
    # set rss in your root config
    # https://github.com/hexojs/hexo-generator-feed
    link: /atom.xml # config.feed.path
    icon: ri:rss-line
    color: orange
  - name: E-Mail
    link: mailto:sun@wuyuan.dev
    icon: ri:mail-line
    color: "#8E71C1"
  - name: å¾®åš
    link: https://weibo.com/wuyuankeji #ä½ çš„å¾®åšä¸»é¡µåœ°å€
    icon: ri:weibo-line
    color: "#E6162D"
  - name: çŸ¥ä¹
    link: https://www.zhihu.com/people/sunwuyuan #ä½ çš„çŸ¥ä¹ä¸»é¡µåœ°å€
    icon: ri:zhihu-line
    color: "#0084FF"
  - name: å“”å“©å“”å“©åŠ¨ç”»
    link: https://space.bilibili.com/661404066 #ä½ çš„Bç«™ä¸»é¡µåœ°å€ï¼ˆæ•°å­—æ¢æˆuuidä¹Ÿå¯ä»¥ï¼‰
    icon: ri:bilibili-line
    color: "#FF8EB3"



banner:
  enable: true
  title: è¯·æŠŠè¿™é‡Œä¿®æ”¹ä¸ºè‡ªå·±çš„ç½‘ç«™åå­—,æ³¨æ„ä¸è¦åˆ é™¤ç©ºæ ¼
  border: true
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line

avatar:
  enable: true
  url: è¯·æŠŠè¿™é‡Œä¿®æ”¹ä¸ºè‡ªå·±çš„å¤´åƒé“¾æ¥
  rounded: true
  opacity: 1
  mickey_mouse: false
  status:
    enable: true
    emoji: ğŸ˜­
    message: ä¸æƒ³ä¸Šå­¦

menu:
  home:
    path: /
    icon: ri:home-4-line
  list:
    - type: archives
      path: /archives/
      icon: ri:archive-line
    - type: categories
      path: /categories/
      icon: ri:folder-2-line
    - type: tags
      path: /tags/
      icon: ri:price-tag-3-line

  custom:
    title: bilibili
    path: https://space.bilibili.com/
    icon: ri:bilibili-line

codeblock:
  copy_btn: true

creative_commons:
  license: by-nc-sa
  post: true
  language: deed.zh
  clipboard: true


footer:
  since: 2022
  icon:
    name: ri:cloud-line
    animated: true
    color: "#0078E7"

  live_time:
    enable: false
    prefix: æœ¬åšå®¢å·²èŒèŒå“’åœ°è¿è¡Œ
    suffix: (â—'â—¡'â—)
    start_time: "2022-01-01T00:00:00"


say:
  enable: true
  api: https://cdn.jsdelivr.net/gh/ElpsyCN/say@gh-pages/sentences.json
  # https://developer.hitokoto.cn/sentence/
  hitokoto:
    enable: true
    api: https://v1.hitokoto.cn

mourn:
  enable: true
  days:
    - 4-4

local_search:
  enable: true

baidu_push: true


pages:
  - name: æˆ‘çš„å°ä¼™ä¼´ä»¬
    url: /links/
    icon: ri:genderless-line
    color: dodgerblue

wordcloud:
  enable: true


